// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/navigation/reverse": {
    params: {};
  };
  "/api/movement/variance": {
    params: {};
  };
  "/api/movement/heading": {
    params: {};
  };
  "/api/navigation/start": {
    params: {};
  };
  "/api/recent-locations": {
    params: {};
  };
  "/api/navigation/stop": {
    params: {};
  };
  "/api/location/reset": {
    params: {};
  };
  "/api/movement/speed": {
    params: {};
  };
  "/api/movement/mode": {
    params: {};
  };
  "/api/movement/step": {
    params: {};
  };
  "/api/movement/type": {
    params: {};
  };
  "/api/tunnel/status": {
    params: {};
  };
  "/api/location/set": {
    params: {};
  };
  "/api/tunnel/start": {
    params: {};
  };
  "/api/tunnel/stop": {
    params: {};
  };
  "/api/gpx/upload": {
    params: {};
  };
  "/api/settings": {
    params: {};
  };
  "/api/devices": {
    params: {};
  };
  "/api/devices/:udid/select": {
    params: {
      "udid": string;
    };
  };
  "/api/devices/:udid/wifi": {
    params: {
      "udid": string;
    };
  };
  "/api/events": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/navigation/reverse" | "/api/movement/variance" | "/api/movement/heading" | "/api/navigation/start" | "/api/recent-locations" | "/api/navigation/stop" | "/api/location/reset" | "/api/movement/speed" | "/api/movement/mode" | "/api/movement/step" | "/api/movement/type" | "/api/tunnel/status" | "/api/location/set" | "/api/tunnel/start" | "/api/tunnel/stop" | "/api/gpx/upload" | "/api/settings" | "/api/devices" | "/api/devices/:udid/select" | "/api/devices/:udid/wifi" | "/api/events";
  };
  "routes/api.navigation.reverse.ts": {
    id: "routes/api.navigation.reverse";
    page: "/api/navigation/reverse";
  };
  "routes/api.movement.variance.ts": {
    id: "routes/api.movement.variance";
    page: "/api/movement/variance";
  };
  "routes/api.movement.heading.ts": {
    id: "routes/api.movement.heading";
    page: "/api/movement/heading";
  };
  "routes/api.navigation.start.ts": {
    id: "routes/api.navigation.start";
    page: "/api/navigation/start";
  };
  "routes/api.recent-locations.ts": {
    id: "routes/api.recent-locations";
    page: "/api/recent-locations";
  };
  "routes/api.navigation.stop.ts": {
    id: "routes/api.navigation.stop";
    page: "/api/navigation/stop";
  };
  "routes/api.location.reset.ts": {
    id: "routes/api.location.reset";
    page: "/api/location/reset";
  };
  "routes/api.movement.speed.ts": {
    id: "routes/api.movement.speed";
    page: "/api/movement/speed";
  };
  "routes/api.movement.mode.ts": {
    id: "routes/api.movement.mode";
    page: "/api/movement/mode";
  };
  "routes/api.movement.step.ts": {
    id: "routes/api.movement.step";
    page: "/api/movement/step";
  };
  "routes/api.movement.type.ts": {
    id: "routes/api.movement.type";
    page: "/api/movement/type";
  };
  "routes/api.tunnel.status.ts": {
    id: "routes/api.tunnel.status";
    page: "/api/tunnel/status";
  };
  "routes/api.location.set.ts": {
    id: "routes/api.location.set";
    page: "/api/location/set";
  };
  "routes/api.tunnel.start.ts": {
    id: "routes/api.tunnel.start";
    page: "/api/tunnel/start";
  };
  "routes/api.tunnel.stop.ts": {
    id: "routes/api.tunnel.stop";
    page: "/api/tunnel/stop";
  };
  "routes/api.gpx.upload.ts": {
    id: "routes/api.gpx.upload";
    page: "/api/gpx/upload";
  };
  "routes/api.settings.ts": {
    id: "routes/api.settings";
    page: "/api/settings";
  };
  "routes/api.devices.ts": {
    id: "routes/api.devices";
    page: "/api/devices" | "/api/devices/:udid/select" | "/api/devices/:udid/wifi";
  };
  "routes/api.devices.$udid.select.ts": {
    id: "routes/api.devices.$udid.select";
    page: "/api/devices/:udid/select";
  };
  "routes/api.devices.$udid.wifi.ts": {
    id: "routes/api.devices.$udid.wifi";
    page: "/api/devices/:udid/wifi";
  };
  "routes/api.events.ts": {
    id: "routes/api.events";
    page: "/api/events";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/api.navigation.reverse": typeof import("./app/routes/api.navigation.reverse.ts");
  "routes/api.movement.variance": typeof import("./app/routes/api.movement.variance.ts");
  "routes/api.movement.heading": typeof import("./app/routes/api.movement.heading.ts");
  "routes/api.navigation.start": typeof import("./app/routes/api.navigation.start.ts");
  "routes/api.recent-locations": typeof import("./app/routes/api.recent-locations.ts");
  "routes/api.navigation.stop": typeof import("./app/routes/api.navigation.stop.ts");
  "routes/api.location.reset": typeof import("./app/routes/api.location.reset.ts");
  "routes/api.movement.speed": typeof import("./app/routes/api.movement.speed.ts");
  "routes/api.movement.mode": typeof import("./app/routes/api.movement.mode.ts");
  "routes/api.movement.step": typeof import("./app/routes/api.movement.step.ts");
  "routes/api.movement.type": typeof import("./app/routes/api.movement.type.ts");
  "routes/api.tunnel.status": typeof import("./app/routes/api.tunnel.status.ts");
  "routes/api.location.set": typeof import("./app/routes/api.location.set.ts");
  "routes/api.tunnel.start": typeof import("./app/routes/api.tunnel.start.ts");
  "routes/api.tunnel.stop": typeof import("./app/routes/api.tunnel.stop.ts");
  "routes/api.gpx.upload": typeof import("./app/routes/api.gpx.upload.ts");
  "routes/api.settings": typeof import("./app/routes/api.settings.ts");
  "routes/api.devices": typeof import("./app/routes/api.devices.ts");
  "routes/api.devices.$udid.select": typeof import("./app/routes/api.devices.$udid.select.ts");
  "routes/api.devices.$udid.wifi": typeof import("./app/routes/api.devices.$udid.wifi.ts");
  "routes/api.events": typeof import("./app/routes/api.events.ts");
  "routes/_index": typeof import("./app/routes/_index.tsx");
};